In [8]:
pip install --upgrade audiofeatures

Requirement already satisfied: audiofeatures in /Users/dhyan/anaconda3/lib/python3.11/site-packages (2.2.0)
Requirement already satisfied: numpy>=1.23 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from audiofeatures) (1.26.4)
Requirement already satisfied: pandas>=2.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from audiofeatures) (2.2.3)
Requirement already satisfied: librosa>=0.10.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from audiofeatures) (0.10.2.post1)
Requirement already satisfied: soundfile>=0.12.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from audiofeatures) (0.12.1)
Requirement already satisfied: audioread>=2.1.9 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (3.0.1)
Requirement already satisfied: scipy>=1.2.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.11.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.3.0)
Requirement already satisfied: joblib>=0.14 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (5.1.1)
Requirement already satisfied: numba>=0.51.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (0.62.1)
Requirement already satisfied: pooch>=1.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (0.5.0.post1)
Requirement already satisfied: typing-extensions>=4.1.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (4.15.0)
Requirement already satisfied: lazy-loader>=0.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (0.4)
Requirement already satisfied: msgpack>=1.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.0.3)
Requirement already satisfied: packaging in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from lazy-loader>=0.1->librosa>=0.10.0->audiofeatures) (26.2)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from numba>=0.51.0->librosa>=0.10.0->audiofeatures) (0.45.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pandas>=2.0->audiofeatures) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pandas>=2.0->audiofeatures) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pandas>=2.0->audiofeatures) (2023.3)
Requirement already satisfied: platformdirs>=2.5.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pooch>=1.1->librosa>=0.10.0->audiofeatures) (4.3.7)
Requirement already satisfied: requests>=2.19.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pooch>=1.1->librosa>=0.10.0->audiofeatures) (2.34.2)
Requirement already satisfied: six>=1.5 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=2.0->audiofeatures) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa>=0.10.0->audiofeatures) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa>=0.10.0->audiofeatures) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa>=0.10.0->audiofeatures) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa>=0.10.0->audiofeatures) (2025.4.26)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from scikit-learn>=0.20.0->librosa>=0.10.0->audiofeatures) (3.5.0)
Requirement already satisfied: cffi>=1.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from soundfile>=0.12.1->audiofeatures) (1.17.1)
Requirement already satisfied: pycparser in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from cffi>=1.0->soundfile>=0.12.1->audiofeatures) (2.21)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from audiofeatures import extract_features

df = extract_features("/Users/dhyan/Desktop/project/audio_emotion/data/DEAM_audio/MEMD_audio/2029.mp3")

print(df.head())

[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed

   window  start_time  end_time       rms       zcr      energy  \
0       0         0.0       0.5  0.174975 -0.881814  337.543915
1       1         0.5       1.0  0.164385 -0.875737  297.921967
2       2         1.0       1.5  0.199982 -0.906757  440.922607
3       3         1.5       2.0  0.163005 -0.919909  292.942932
4       4         2.0       2.5  0.118389 -0.948662  154.526489

   peak_amplitude  crest_factor  dynamic_range  energy_variability  ...  \
0        0.688580      3.935305       1.324150            0.007810  ...
1        0.735711      4.475535       1.304316            0.008052  ...
2        0.965982      4.830335       1.684835            0.014934  ...
3        0.558363      3.425425       1.043274            0.002669  ...
4        0.385103      3.252851       0.763867            0.001843  ...

   tonnetz_5_std  tonnetz_6_mean  tonnetz_6_std  pitch_mean   pitch_std  \
0       0.037648       -0.000012       0.033608  278.920523  382.787451
1       0.020815        0.030322       0.033582  165.186512  260.213660
2       0.045187        0.002682       0.042099  113.786250   53.322705
3       0.027804        0.010669       0.022132  104.605026   23.497671
4       0.008202        0.006401       0.008203  129.621546  181.211499

    pitch_min    pitch_max  onset_strength_mean  onset_strength_std  \
0  110.219688  1750.245988             1.909868            2.809083
1   75.146566  1348.068273             1.067422            0.808073
2   66.347331   263.608493             1.042589            0.718718
3   76.846747   200.625953             0.727136            0.589929
4   87.686350   959.662451             0.654995            0.478723

   onset_strength_max
0           12.817518
1            3.133555
2            3.075953
3            3.148324
4            2.390371

[5 rows x 185 columns]

In [5]:
df

,window,start_time,end_time,rms,zcr,energy,peak_amplitude,crest_factor,dynamic_range,energy_variability,...,tonnetz_5_std,tonnetz_6_mean,tonnetz_6_std,pitch_mean,pitch_std,pitch_min,pitch_max,onset_strength_mean,onset_strength_std,onset_strength_max
0,0,0.0,0.5,0.174975,-0.881814,337.543915,0.688580,3.935305,1.324150,0.007810,...,0.037648,-0.000012,0.033608,278.920523,382.787451,110.219688,1750.245988,1.909868,2.809083,12.817518
1,1,0.5,1.0,0.164385,-0.875737,297.921967,0.735711,4.475535,1.304316,0.008052,...,0.020815,0.030322,0.033582,165.186512,260.213660,75.146566,1348.068273,1.067422,0.808073,3.133555
2,2,1.0,1.5,0.199982,-0.906757,440.922607,0.965982,4.830335,1.684835,0.014934,...,0.045187,0.002682,0.042099,113.786250,53.322705,66.347331,263.608493,1.042589,0.718718,3.075953
3,3,1.5,2.0,0.163005,-0.919909,292.942932,0.558363,3.425425,1.043274,0.002669,...,0.027804,0.010669,0.022132,104.605026,23.497671,76.846747,200.625953,0.727136,0.589929,3.148324
4,4,2.0,2.5,0.118389,-0.948662,154.526489,0.385103,3.252851,0.763867,0.001843,...,0.008202,0.006401,0.008203,129.621546,181.211499,87.686350,959.662451,0.654995,0.478723,2.390371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,332,166.0,166.5,0.184449,-0.911293,375.084869,0.965139,5.232563,1.841989,0.012956,...,0.039675,-0.006653,0.030451,195.640233,439.051235,69.958662,2205.000000,0.905251,0.894225,3.478344
333,333,166.5,167.0,0.153527,-0.915283,259.866302,0.624355,4.066736,1.241452,0.006177,...,0.009183,0.008482,0.015718,190.477025,439.876019,76.740588,2205.000000,0.957667,0.692736,2.643271
334,334,167.0,167.5,0.167818,-0.916735,310.497040,0.977520,5.824868,1.800506,0.017847,...,0.048328,0.014508,0.039623,199.190439,383.558899,77.623190,1947.020150,0.776911,0.795589,3.197873
335,335,167.5,168.0,0.052390,-0.937868,30.260244,0.185054,3.532251,0.360469,0.000816,...,0.023992,0.002288,0.018714,235.399289,191.846901,111.917310,1104.531216,0.641741,0.435996,2.102888
336,336,168.0,168.5,0.032140,-0.967891,11.388441,0.092903,2.890606,0.185225,0.000126,...,0.020148,-0.003530,0.013083,248.130281,109.068348,220.278276,747.730519,0.827659,0.636711,3.244354

In [9]:
from audiofeatures import extract_dataset

df = extract_dataset(
    dataset_path="/Users/dhyan/Desktop/project/test data",
    output_csv="/Users/dhyan/Desktop/project/test data"
)

TypeError: extract_dataset() got an unexpected keyword argument 'dataset_path'

In [10]:
from audiofeatures import extract_dataset

print(extract_dataset)

<function extract_dataset at 0x104418400>

In [1]:
pip install audiofeatures==2.3.0

ERROR: Could not find a version that satisfies the requirement audiofeatures==2.3.0 (from versions: 0.1.0, 0.1.2, 0.1.5, 0.1.6, 2.2.0)
ERROR: No matching distribution found for audiofeatures==2.3.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
python -m pip install --upgrade audiofeatures

SyntaxError: invalid syntax (1787412689.py, line 1)

In [3]:
pip install --upgrade audiofeatures

Requirement already satisfied: audiofeatures in /Users/dhyan/anaconda3/lib/python3.11/site-packages (2.2.0)
Requirement already satisfied: numpy>=1.23 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from audiofeatures) (1.26.4)
Requirement already satisfied: pandas>=2.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from audiofeatures) (2.2.3)
Requirement already satisfied: librosa>=0.10.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from audiofeatures) (0.10.2.post1)
Requirement already satisfied: soundfile>=0.12.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from audiofeatures) (0.12.1)
Requirement already satisfied: audioread>=2.1.9 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (3.0.1)
Requirement already satisfied: scipy>=1.2.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.11.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.3.0)
Requirement already satisfied: joblib>=0.14 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (5.1.1)
Requirement already satisfied: numba>=0.51.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (0.62.1)
Requirement already satisfied: pooch>=1.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (0.5.0.post1)
Requirement already satisfied: typing-extensions>=4.1.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (4.15.0)
Requirement already satisfied: lazy-loader>=0.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (0.4)
Requirement already satisfied: msgpack>=1.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from librosa>=0.10.0->audiofeatures) (1.0.3)
Requirement already satisfied: packaging in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from lazy-loader>=0.1->librosa>=0.10.0->audiofeatures) (26.2)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from numba>=0.51.0->librosa>=0.10.0->audiofeatures) (0.45.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pandas>=2.0->audiofeatures) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pandas>=2.0->audiofeatures) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pandas>=2.0->audiofeatures) (2023.3)
Requirement already satisfied: platformdirs>=2.5.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pooch>=1.1->librosa>=0.10.0->audiofeatures) (4.3.7)
Requirement already satisfied: requests>=2.19.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from pooch>=1.1->librosa>=0.10.0->audiofeatures) (2.34.2)
Requirement already satisfied: six>=1.5 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=2.0->audiofeatures) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa>=0.10.0->audiofeatures) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa>=0.10.0->audiofeatures) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa>=0.10.0->audiofeatures) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa>=0.10.0->audiofeatures) (2025.4.26)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from scikit-learn>=0.20.0->librosa>=0.10.0->audiofeatures) (3.5.0)
Requirement already satisfied: cffi>=1.0 in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from soundfile>=0.12.1->audiofeatures) (1.17.1)
Requirement already satisfied: pycparser in /Users/dhyan/anaconda3/lib/python3.11/site-packages (from cffi>=1.0->soundfile>=0.12.1->audiofeatures) (2.21)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import audiofeatures

print(audiofeatures.__file__)

/Users/dhyan/Desktop/project/audio_emotion/project/pypi-audiofeatures/audiofeatures/__init__.py

In [5]:
import importlib.metadata

print(importlib.metadata.version("audiofeatures"))

2.3.0

In [6]:
from audiofeatures import extract_dataset

df = extract_dataset(
    dataset_path="/Users/dhyan/Desktop/project/test data",
    output_csv="/Users/dhyan/Desktop/project/test data"
)

TypeError: extract_dataset() got an unexpected keyword argument 'dataset_path'

In [7]:
from audiofeatures import extract_dataset

df = extract_dataset(
    audio_folder="/Users/dhyan/Desktop/project/test data"
)

df.head()

[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed
[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed
[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed
[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed
[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed
[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed
[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed
[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed
[INFO] Loading audio
[INFO] Applying preprocessing
[INFO] Splitting audio into windows
[INFO] Extracting features
[INFO] Feature extraction completed

,window,start_time,end_time,rms,zcr,energy,peak_amplitude,crest_factor,dynamic_range,energy_variability,...,tonnetz_6_std,pitch_mean,pitch_std,pitch_min,pitch_max,onset_strength_mean,onset_strength_std,onset_strength_max,song_id,filename
0,0,0.0,0.5,0.033188,-0.950295,12.143079,0.119136,3.589781,0.227410,0.000226,...,0.012707,130.671634,145.712951,82.696402,795.439663,0.668256,0.788445,3.584089,2003,2003.mp3
1,1,0.5,1.0,0.045797,-0.954014,23.123199,0.192209,4.197001,0.379708,0.001630,...,0.014905,301.930579,399.422926,82.887518,2057.934858,0.943649,1.585881,7.172695,2003,2003.mp3
2,2,1.0,1.5,0.059783,-0.941043,39.403748,0.323361,5.408894,0.588701,0.003314,...,0.017927,198.101111,162.416809,65.990289,665.614524,1.274784,2.273388,9.305988,2003,2003.mp3
3,3,1.5,2.0,0.054512,-0.939501,32.761990,0.243933,4.474807,0.411284,0.001238,...,0.023462,208.128813,334.621983,65.983781,1688.073166,1.212471,1.113051,4.060335,2003,2003.mp3
4,4,2.0,2.5,0.069843,-0.955918,53.780380,0.396815,5.681537,0.708642,0.005411,...,0.018030,188.310505,64.507365,166.065922,480.211946,1.261878,2.150681,9.913329,2003,2003.mp3

In [8]:
df

,window,start_time,end_time,rms,zcr,energy,peak_amplitude,crest_factor,dynamic_range,energy_variability,...,tonnetz_6_std,pitch_mean,pitch_std,pitch_min,pitch_max,onset_strength_mean,onset_strength_std,onset_strength_max,song_id,filename
0,0,0.0,0.5,0.033188,-0.950295,12.143079,0.119136,3.589781,0.227410,0.000226,...,0.012707,130.671634,145.712951,82.696402,795.439663,0.668256,0.788445,3.584089,2003,2003.mp3
1,1,0.5,1.0,0.045797,-0.954014,23.123199,0.192209,4.197001,0.379708,0.001630,...,0.014905,301.930579,399.422926,82.887518,2057.934858,0.943649,1.585881,7.172695,2003,2003.mp3
2,2,1.0,1.5,0.059783,-0.941043,39.403748,0.323361,5.408894,0.588701,0.003314,...,0.017927,198.101111,162.416809,65.990289,665.614524,1.274784,2.273388,9.305988,2003,2003.mp3
3,3,1.5,2.0,0.054512,-0.939501,32.761990,0.243933,4.474807,0.411284,0.001238,...,0.023462,208.128813,334.621983,65.983781,1688.073166,1.212471,1.113051,4.060335,2003,2003.mp3
4,4,2.0,2.5,0.069843,-0.955918,53.780380,0.396815,5.681537,0.708642,0.005411,...,0.018030,188.310505,64.507365,166.065922,480.211946,1.261878,2.150681,9.913329,2003,2003.mp3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4169,694,347.0,347.5,0.036697,-0.926349,14.846848,0.120637,3.287388,0.236556,0.000151,...,0.042148,431.672480,170.339694,229.456158,1047.598573,0.719480,0.370593,1.707740,2012,2012.mp3
4170,695,347.5,348.0,0.031623,-0.927256,11.025298,0.120056,3.796454,0.232551,0.000110,...,0.032686,430.015604,412.096185,68.224293,2205.000000,0.907157,0.667152,2.834289,2012,2012.mp3
4171,696,348.0,348.5,0.028740,-0.912109,9.106710,0.103263,3.592957,0.196806,0.000081,...,0.048254,401.368463,229.985928,67.612239,1310.810258,1.251420,0.851412,3.201937,2012,2012.mp3
4172,697,348.5,349.0,0.027913,-0.919274,8.589802,0.105583,3.782627,0.201581,0.000171,...,0.035777,414.530290,67.531248,215.519955,550.575829,0.743435,0.443327,2.218923,2012,2012.mp3
4173,698,349.0,349.5,0.026733,-0.925986,7.878810,0.091666,3.428990,0.175372,0.000066,...,0.065963,352.250672,142.184215,80.189007,478.218828,0.792548,0.584460,3.058472,2012,2012.mp3